#include "../kal/platform.hpp"
#include "driver.hpp"
#include <iostream>
#include <string>
#include <vector>

/*!
 * entry point for the Qvickbuild binary. this simply fetches the arguments
 * passed on by the shell and sends them off to the driver.
 * \return EXIT_SUCCESS if build finished properly, EXIT_FAILURE on failure -
 * regardless of whether the failure was generated by user error, build error,
 * or a internal exception.
 */

int main(int argc, char **argv) {
  // collect all arguments (except first which is the binary).
  std::vector<std::string> args(argv + 1, argv + argc);

  // parse arguments to setup driver.
  Setup setup = Driver::default_setup();
  for (auto arg_it = args.begin(); arg_it != args.end(); arg_it++) {
    if (*arg_it == "--stdin") {
      setup.input_method = InputMethod::Stdin;
    } else if (*arg_it == "--configfile") {
      setup.input_method = InputMethod::ConfigFile;
      arg_it++;
      if (arg_it == args.end()) {
        std::cerr << "error: no config file was specified. cannot proceed."
                  << std::endl;
        exit(EXIT_FAILURE);
      }
      setup.input_file = *arg_it;
    } else if (*arg_it == "--log-quiet") {
      setup.logging_level = LogLevel::Quiet;
    } else if (*arg_it == "--log-standard") {
      setup.logging_level = LogLevel::Standard;
    } else if (*arg_it == "--log-verbose") {
      setup.logging_level = LogLevel::Verbose;
    } else if (*arg_it == "--dry-run") {
      setup.dry_run = true;
    } else if (*arg_it == "--version") {
      std::cout << "qvickbuild " << KALPlatform::get_version_string()
                << std::endl;
      exit(EXIT_SUCCESS);
    } else if (*arg_it == "--help") {
      std::cout << "Usage: qvickbuild [arguments] [task]\n"
                   "Arguments:\n"
                   "  --stdin: reads config from stdin\n"
                   "  --configfile [file]: reads config from specified file\n"
                   "  --log-quiet: sets logging level to quiet\n"
                   "  --log-standard: sets logging level to standard\n"
                   "  --log-verbose: sets logging level to verbose\n"
                   "  --dry-run: prevents the execution of any commands\n"
                   "  --version: emits qvickbuild version\n"
                   "  --help: shows this message and exits\n";
      exit(EXIT_SUCCESS);
    } else if (!setup.task) {
      setup.task = *arg_it;
    } else {
      std::cerr << "error: more than one task was specified. cannot proceed."
                << std::endl;
      exit(EXIT_FAILURE);
    }
  }

  // run driver.
  try {
    Driver driver = Driver(setup);
    return driver.run();
  } catch (const std::exception &e) {
    std::cerr << "! <Fatal crash>\n! The Qvickbuild driver threw an unhandled"
                 "exception. This is an internal bug and should be reported."
              << std::endl;
    std::cerr << "! Error data: " << e.what() << std::endl;
    exit(EXIT_FAILURE);
  }
}
